### ISSUE TITLE
how to know the hex from     " iv = bytes.fromhex("A0 47 E9 3D 23 0A 4C 62 A7 44 B1 A4 EE 85 7F BA")"

### ISSUE THREAD

**Issue by qwertroot12345** [blluv/pgmm_decrypt#1]
[pgmm_decrypt]

(https://github.com/blluv/pgmm_decrypt)/dec_resource.py line22:
iv = bytes.fromhex("A0 47 E9 3D 23 0A 4C 62 A7 44 B1 A4 EE 85 7F BA")

**Comment by blluv** [comment]
iv is fixed data

**Comment by blluv** [comment]
by reversing :)
