### ISSUE TITLE
 Games with custom encryption keys cannot be extracted.

### ISSUE THREAD

**Issue by YeziTl** [blluv/pgmm_decrypt#2]
Using "dec_resource.py," I can extract encrypted game resources, but when the game has the encryption key  enabled, the extracted game files still cannot be read. I hope to get assistance with this issue.

**Comment by blluv** [comment]
Sorry for the late reply.
To decrypt the resource, you need to decrypt the info.json using dec_too_short_key.py and then get the password.

If the decrypted password is too small for the Twofish key schedule (I don't remember the exact size), you can use dec_too_short_key.py to decrypt the resource, but that doesn't seem to be the case in your situation.

I think that if you put the decrypted password in the decrypted_key in dec_resource.py file, you can decrypt the resource.

If that doesn't work, please send the game files to biluv@protonmail.com.
