### ISSUE TITLE
Add a tutorial for beginners who don't know how this tool works...?

### ISSUE THREAD

**Issue by AnotherBlob** [blluv/pgmm_decrypt#3]
Hello, this seems to be a tool that lets a user decrypt assets for a Pixel Game Maker MV game, right? But I don't understand how this program works, could a guide be made that follows through step by step how to decrypt an asset for a game?
Sorry that this isn't a bug report but I think reporting that the usability of this tool is poor to people who might not understand Python usage much and who would just want to decrypt assets is also a bit necessary here.

**Comment by blluv** [comment]
This manual is based on my memory.

I don't currently have your PGMM game data, so it's hard for me to help you with any issues.

If you encounter any issues, please send encrypted resources and info.json to biluv@protonmail.com.

# 1. Install Package
```
pip3 install git+https://github.com/blluv/pgmm_decrypt.git
```

# 2. Decrypt Key
```
import base64
from pgmm_decrypt import decrypt_pgmm_key, decrypt_pgmm_resource

key = decrypt_pgmm_key(base64.b64decode("ENCRYPTED_PASSWORD_IN_INFO_JSON"))
```

# 3. Decrypt Resource

```
encrypted_resource = open("path_to_resource", "rb).read()

# Weak
decrypted_res_typeA = decrypt_pgmm_resource(key, encrypted_resource, True)
open("decrypted_typeA", "wb).write(decrypted_res_typeA)

# Not Weak
decrypted_res_typeB = decrypt_pgmm_resource(key, encrypted_resource, False)
open("decrypted_typeB", "wb).write(decrypted_res_typeB)
```

**Comment by blluv** [comment]
This manual is based on my memory.

I don't currently have PGMM game data, so it's hard for me to help you with any issues.

If you encounter any issues, please send encrypted resources and info.json to biluv@protonmail.com.

# 1. Install Package
```
pip3 install git+https://github.com/blluv/pgmm_decrypt.git
```

# 2. Decrypt Key
```py
import base64
from pgmm_decrypt import decrypt_pgmm_key, decrypt_pgmm_resource

key = decrypt_pgmm_key(base64.b64decode("ENCRYPTED_PASSWORD_IN_INFO_JSON"))
```

# 3. Decrypt Resource

```py
encrypted_resource = open("path_to_resource", "rb).read()

# Weak
decrypted_res_typeA = decrypt_pgmm_resource(key, encrypted_resource, True)
open("decrypted_typeA", "wb).write(decrypted_res_typeA)

# Not Weak
decrypted_res_typeB = decrypt_pgmm_resource(key, encrypted_resource, False)
open("decrypted_typeB", "wb).write(decrypted_res_typeB)
```
